apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-deployment
  namespace: ci-cd
spec:
  selector:
    matchLabels:
      app: spring-ci-cd-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-ci-cd-k8s
    spec:
      containers:
        - name: my-container
          image: niitrajnish/spring-ci-cd:1.0
          imagePullPolicy: IfNotPresent
          port:
            - containerPort: 9090
