apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: my-container
          image: niitrajnish/spring-ci-cd:1.0
          imagePullPolicy: IfNotPresent
          port: 9090
