apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
  labels:
    name: ci-cd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-deployment
  namespace: ci-cd
spec:
  selector:
    matchLabels:
      app: spring-ci-cd-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-ci-cd-k8s
    spec:
      containers:
        - name: my-container
          image: niitrajnish/spring-ci-cd:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-service
  namespace: ci-cd
spec:
  selector:
    app: spring-ci-cd-k8s
  ports:
    - protocol: "TCP"
      port: 8181
      targetPort: 9090
  type: NodePort