apiVersion: v1
kind: service
metadata:
  name: spring-k8s-service
  namespace: development
spec:
  selector:
    app: spring-k8s
  ports:
    - protocols: TCP
      port: 8181
      targetPort: 9090
  type: NodePort