apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-service
  namespace: ci-cd
spec:
  selector:
    app: spring-ci-cd-k8s
  ports:
    - protocol: "TCP"
      port: 8181
      targetPort: 9090
  type: NodePort